apiVersion: v1
kind: Service
metadata:
  name: hello-world-np-service
spec:
  type: NodePort
  selector:
    app: hello-world
  ports:
  - nodePort: 32410
    protocol: TCP
    port: 8080
    targetPort: 8080
