apiVersion: v1
kind: Service
metadata:
  name: hello-world-lb-service
spec:
  type: LoadBalancer
  selector:
    app: hello-world
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
  externalIPs:
  - 192.168.49.2  
