apiVersion: v1
kind: Pod
metadata:
  name: pod-example
  labels:
    app: nginx
  annotations:
    description: "nginx demo pod"
spec:
  containers:
  - name: nginx
    image: nginx:stable-alpine
    ports:
    - containerPort: 80
