version: '3.3'
services:
#   zookeeper:
#     image: 'bitnami/zookeeper:latest'
#     container_name: zookeeper
#     ports:
#       - '2181:2181'
#     environment:
#       - ALLOW_ANONYMOUS_LOGIN=yes
#     networks:
#       - scart  
#             
#   kafka:
#     image: 'bitnami/kafka:latest'
#     container_name: kafka
#     ports:
#       - '9092:9092'
#     environment:
#       - KAFKA_BROKER_ID=1
#       - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
#       - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://127.0.0.1:9092
#       - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
#       - ALLOW_PLAINTEXT_LISTENER=yes
#     depends_on:
#       - zookeeper 
#     networks:
#       - scart           
  
  registry-service:
      image: dockrtraining/registry-service
      container_name: registry-service
      ports:
        - 8761:8761
      networks:
      - scart  
  
  gateway-service:
      image: dockrtraining/gateway-service
      container_name: gateway-service
      ports:
        - 8111:8111 
      depends_on:
      - registry-service
      networks:
      - scart
      environment:
        REGISTRY_SERVER_HOST: registry-service
  
#   customer-service:
#       image: dockrtraining/customer-service
#       container_name: customer-service
#       ports:
#         - 8092:8092 
#       depends_on:
#       - gateway-service
#       networks:
#       - scart  
#       environment:
#         REGISTRY_SERVER_HOST: registry-service
#         KAFKA_BOOTSTRAP_SERVERS:  kafka:9092    
#   
#   order-service:
#       image: dockrtraining/order-service
#       container_name: order-service
#       ports:
#         - 8093:8093  
#       depends_on:
#       - gateway-service
#       networks:
#       - scart  
#       environment:
#         REGISTRY_SERVER_HOST: registry-service
#         KAFKA_BOOTSTRAP_SERVERS:  kafka:9092  

  product-service:
      image: dockrtraining/product-service
      container_name: product-service
      ports:
        - 8091:8091 
      depends_on:
      - gateway-service
      networks:
      - scart  
      environment:
        REGISTRY_SERVER_HOST: registry-service
         
  admin-service:
      image: dockrtraining/admin-service
      container_name: admin-service
      restart: always 
      ports:
        - 7777:7777 
      depends_on:
      - gateway-service
      networks:
      - scart  
      environment:
        REGISTRY_SERVER_HOST: registry-service                 
       
networks:
  scart: