apiVersion: v1
kind: Service
metadata:
  name: product-service
  labels:
    app: product-service
spec:
  type: LoadBalancer
  selector:
    app: product-service  
  ports:
  - port: 8091
  externalIPs:
  - 172.17.0.103
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-service
  labels:
    app: product-service
spec:
  replicas: 3
  selector:
    matchLabels:
      app: product-service
  template:
    metadata:
      labels:
        app: product-service
    spec:
      containers:
      - name: product-service
        image: dockrtraining/scart-product-service:v1
        ports:
        - containerPort: 8091
        env:
        - name: REGISTRY_SERVER_HOST
          value: 10.97.214.28      