spring:
  application:
    name: registry-service

server:
  port: 8761

#Eureka Server Config
eureka:
  client:
    fetch-registry: false
    register-with-eureka: false

#Expose all Actuator endpoints
management:
  endpoints:
    web:
      exposure:
        include: "*"